<?php
if (!defined('_GNUBOARD_')) exit;
$menu=array (
  0 => 
  array (
    'text' => '페이지',
	'href' => short_url_clean(G5_BBS_URL.'/group.php?gr_id=basic'),
	'icon' => 'empty',
	'target' => '_self',
	'line' => '',
	'sp' => '',
	'limit' => '',
	'grade' => 0,
	'id' => G5_BBS_DIR.'-group-basic',
	'gr_id' => 'basic',
	's' => 
    array (
      0 => 
      array (
        'text' => '그룹메인',
        'href' => short_url_clean(G5_BBS_URL.'/group.php?gr_id=basic'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-group-basic',
        'gr_id' => 'basic',
      ),
	  1 => 
      array (
        'text' => '새글모음',
        'href' => G5_BBS_URL.'/new.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-new',
      ),
	  2 => 
      array (
        'text' => '태그모음',
        'href' => G5_BBS_URL.'/tag.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-tag',
      ),
	  3 => 
      array (
        'text' => '전체검색',
        'href' => G5_BBS_URL.'/search.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-search',
      ),
	  4 => 
      array (
        'text' => 'FAQ',
        'href' => G5_BBS_URL.'/faq.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-faq',
      ),
      5 => 
      array (
        'text' => '접속자',
        'href' => G5_BBS_URL.'/current_connect.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-current_connect',
      ),
      6 => 
      array (
        'text' => '알림모음',
        'href' => G5_BBS_URL.'/noti.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '회원전용',
        'sp' => '1',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-noti',
      ),
	  7 => 
      array (
        'text' => '신고모음',
        'href' => G5_BBS_URL.'/shingo.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-shingo',
      ),
      8 => 
      array (
        'text' => '1:1문의',
        'href' => G5_BBS_URL.'/qalist.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-qa',
      ),
    ),
  ),
  1 => 
  array (
	'text' => '글목록',
	'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=video&demo=basic'),
	'icon' => 'empty',
	'target' => '_self',
	'line' => '',
	'sp' => '',
	'limit' => '',
	'grade' => 0,
	'id' => G5_BBS_DIR.'-board-video-basic',
	'bo_table' => 'video',
	'wr_id' => NULL,
	'sca' => NULL,
    's' => 
    array (
      0 => 
      array (
        'text' => '리스트형',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=video&demo=basic'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-video-basic',
		'bo_table' => 'video',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '갤러리형',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=video&demo=gallery'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-video-gallery',
		'bo_table' => 'video',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '웹진형',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=video&demo=webzine'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-video-webzine',
		'bo_table' => 'video',
		'wr_id' => NULL,
		'sca' => NULL,
	  ),
      3 => 
      array (
        'text' => '웹진 SM형',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=video&demo=webzine-sm'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-video-webzine-sm',
		'bo_table' => 'video',
		'wr_id' => NULL,
		'sca' => NULL,
	  ),
	),
  ),
  2 => 
  array (
	'text' => '게시판',
	'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=basic'),
	'icon' => 'empty',
	'target' => '_self',
	'line' => '',
	'sp' => '',
	'limit' => '',
	'grade' => 0,
	'id' => G5_BBS_DIR.'-board-basic',
	'bo_table' => 'basic',
	'wr_id' => NULL,
	'sca' => NULL,
    's' => 
    array (
      0 => 
      array (
        'text' => '기본 보드',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=basic'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-basic',
		'bo_table' => 'basic',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '피드 보드',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=feed'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-feed',
		'bo_table' => 'feed',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      2 => 
      array (
        'text' => '자료실 보드',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=download'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-download',
		'bo_table' => 'download',
		'wr_id' => NULL,
		'sca' => NULL,
	  ),
      3 => 
      array (
        'text' => '챕터 보드',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=chapter'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-chapter',
		'bo_table' => 'chapter',
		'wr_id' => NULL,
		'sca' => NULL,
	  ),
      4 => 
      array (
        'text' => '1:1 보드',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=1vs1'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-1vs1',
		'bo_table' => '1vs1',
		'wr_id' => NULL,
		'sca' => NULL,
	  ),
      5 => 
      array (
        'text' => '태그 보드',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=tag'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-tag',
		'bo_table' => 'tag',
		'wr_id' => NULL,
		'sca' => NULL,
	  ),
      6 => 
      array (
        'text' => '유튜브 보드',
        'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=youtube'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => G5_BBS_DIR.'-board-youtube',
		'bo_table' => 'youtube',
		'wr_id' => NULL,
		'sca' => NULL,
	  ),
	),
  ),
  3 => 
  array (
    'text' => '자료실',
    'href' => 'https://amina.co.kr/bbs/board.php?bo_table=nariya',
    'icon' => 'empty',
    'target' => '_blank',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
    's' => 
    array (
      0 => 
      array (
        'text' => '나리야 빌더',
        'href' => 'https://amina.co.kr/bbs/board.php?bo_table=nariya',
        'icon' => 'empty',
        'target' => '_blank',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      1 => 
      array (
        'text' => '배포 자료실',
        'href' => 'https://amina.co.kr/bbs/board.php?bo_table=nariya_skin',
        'icon' => 'empty',
        'target' => '_blank',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      2 => 
      array (
        'text' => '그누5 자료실',
        'href' => 'https://amina.co.kr/bbs/board.php?bo_table=nariya_g5',
        'icon' => 'empty',
        'target' => '_blank',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      3 => 
      array (
        'text' => '영카트5 자료실',
        'href' => 'https://amina.co.kr/bbs/board.php?bo_table=nariya_yc5',
        'icon' => 'empty',
        'target' => '_blank',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
      4 => 
      array (
        'text' => '다른 테마 보기',
        'href' => 'https://amina.co.kr/shop/list.php?ca_id=1080',
        'icon' => 'empty',
        'target' => '_blank',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => 'link',
      ),
	),
  ),
);