<?php
if (!defined('_GNUBOARD_')) exit;

global $config;

$menu=array (
  0 => 
  array (
	'text' => '스타일',
	'href' => na_url('./index.php?pvf=Dotum-12px'),
	'icon' => 'empty',
	'target' => '_self',
	'line' => '',
	'sp' => '',
	'limit' => '',
	'grade' => 0,
	'id' => '',
	'bo_table' => NULL,
	'wr_id' => NULL,
	'sca' => NULL,
    's' => 
    array (
      0 => 
      array (
		'text' => 'PC 돋움',
		'href' => na_url('./index.php?pvf=Dotum-12px'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '폰트셋',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      1 => 
      array (
		'text' => 'PC 나눔고딕',
		'href' => na_url('./index.php?pvf=Nanum-Gothic-14px'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      2 => 
      array (
		'text' => 'PC 나눔명조',
		'href' => na_url('./index.php?pvf=Nanum-Myeongjo-14px'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      3 => 
      array (
		'text' => 'PC 넥슨 고딕',
		'href' => na_url('./index.php?pvf=NEXON-Gothic-14px'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      4 => 
      array (
		'text' => 'PC 고딕',
		'href' => na_url('./index.php?pvf=Gothic-14px'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      5 => 
      array (
		'text' => 'PC Roboto',
		'href' => na_url('./index.php?pvf=Roboto-14px'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      6 => 
      array (
		'text' => 'Aqua',
		'href' => na_url('./index.php?pvc=Aqua'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '컬러셋',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      7 => 
      array (
		'text' => 'Bittersweet',
		'href' => na_url('./index.php?pvc=Bittersweet'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      8 => 
      array (
		'text' => 'Black',
		'href' => na_url('./index.php?pvc=Black'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      9 => 
      array (
		'text' => 'Blue',
		'href' => na_url('./index.php?pvc=Blue'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      10 => 
      array (
		'text' => 'Blue-Jeans',
		'href' => na_url('./index.php?pvc=Blue-Jeans'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      11 => 
      array (
		'text' => 'Cyan',
		'href' => na_url('./index.php?pvc=Cyan'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      12 => 
      array (
		'text' => 'Dark',
		'href' => na_url('./index.php?pvc=Dark'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      13 => 
      array (
		'text' => 'Grapefruit',
		'href' => na_url('./index.php?pvc=Grapefruit'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      14 => 
      array (
		'text' => 'Grass',
		'href' => na_url('./index.php?pvc=Grass'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      15 => 
      array (
		'text' => 'Gray',
		'href' => na_url('./index.php?pvc=Gray'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      16 => 
      array (
		'text' => 'Green',
		'href' => na_url('./index.php?pvc=Green'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      17 => 
      array (
		'text' => 'Lavender',
		'href' => na_url('./index.php?pvc=Lavender'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      18 => 
      array (
		'text' => 'Mint',
		'href' => na_url('./index.php?pvc=Mint'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      19 => 
      array (
		'text' => 'Navy',
		'href' => na_url('./index.php?pvc=Navy'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      20 => 
      array (
		'text' => 'Pink-Rose',
		'href' => na_url('./index.php?pvc=Pink-Rose'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      21 => 
      array (
		'text' => 'Red',
		'href' => na_url('./index.php?pvc=Red'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      22 => 
      array (
		'text' => 'Sunflower',
		'href' => na_url('./index.php?pvc=Sunflower'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => '',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
	),
  ),
  1 => 
  array (
	'text' => '인덱스',
	'href' => na_url('./index.php?demo=index-basic-lg'),
	'icon' => 'empty',
	'target' => '_self',
	'line' => '',
	'sp' => '',
	'limit' => '',
	'grade' => 0,
	'id' => 'root-page-index-index-basic-lg',
	'bo_table' => NULL,
	'wr_id' => NULL,
	'sca' => NULL,
    's' => 
    array (
      0 => 
      array (
        'text' => 'Index-Basic-lg',
        'href' => na_url('./index.php?demo=index-basic-lg'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'root-page-index-index-basic-lg',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      1 => 
      array (
        'text' => 'Index-Basic-xl',
        'href' => na_url('./index.php?demo=index-basic-xl'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'root-page-index-index-basic-xl',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      2 => 
      array (
        'text' => 'Index-Basic',
        'href' => na_url('./index.php?demo=index-basic'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'root-page-index-index-basic',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      3 => 
      array (
        'text' => 'Index-One',
        'href' => na_url('./index.php?demo=index-one'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'root-page-index-index-one',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      4 => 
      array (
        'text' => 'Index-One-xl',
        'href' => na_url('./index.php?demo=index-one-xl'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'root-page-index-index-one-xl',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      5 => 
      array (
        'text' => 'Index-Left',
        'href' => na_url('./index.php?demo=index-left'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'root-page-index-index-left',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      6 => 
      array (
        'text' => 'Index-Left-lg',
        'href' => na_url('./index.php?demo=index-left-lg'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'root-page-index-index-left-lg',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      7 => 
      array (
        'text' => 'Index-Left-xl',
        'href' => na_url('./index.php?demo=index-left-xl'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'root-page-index-index-left-xl',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
	),
  ),
  2 => 
  array (
	'text' => '관리자',
	'href' => na_url('../adm/site_setup.php?mode=bbs'),
	'icon' => 'empty',
	'target' => '_self',
	'line' => '',
	'sp' => '',
	'limit' => '',
	'grade' => 0,
	'id' => 'theme-'.$config['cf_theme'].'-adm-page-site_setup',
	'bo_table' => NULL,
	'wr_id' => NULL,
	'sca' => NULL,
    's' => 
    array (
      0 => 
      array (
        'text' => '사이트 설정',
        'href' => na_url('../adm/site_setup.php?mode=bbs'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'theme-'.$config['cf_theme'].'-adm-page-site_setup',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      1 => 
      array (
        'text' => '메뉴 설정',
        'href' => na_url('../adm/menu_form.php?mode=bbs'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
		'id' => 'theme-'.$config['cf_theme'].'-adm-page-menu_form',
		'bo_table' => NULL,
		'wr_id' => NULL,
		'sca' => NULL,
      ),
	),
  ),
  3 => 
  array (
	'text' => '게시판',
	'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Basic'),
	'icon' => 'empty',
	'target' => '_self',
	'line' => '',
	'sp' => '',
	'limit' => '',
	'grade' => 0,
	'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Basic',
	'bo_table' => 'board',
	'wr_id' => NULL,
	'sca' => NULL,
    's' => 
    array (
      0 => 
      array (
		'text' => '리스트 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-Basic-List'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '기본 보드',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-Basic-List',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      1 => 
      array (
		'text' => '갤러리 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-Basic-Gallery'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-Basic-Gallery',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      2 => 
      array (
		'text' => '웹진 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-Basic-Webzine'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-Basic-Webzine',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
	  3 => 
      array (
		'text' => '베이직 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Basic'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '특수 보드',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Basic',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      4 => 
      array (
		'text' => '자료실 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-PDS'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-PDS',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      5 => 
      array (
		'text' => '익명 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=anonymity&bo_skin=BS4-MBS-Anonymity'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-anonymity-BS4-MBS-Anonymity',
		'bo_table' => 'anonymity',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      6 => 
      array (
		'text' => '챕터 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Chapter'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Chapter',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      7 => 
      array (
		'text' => '연재 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Serial'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Serial',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      8 => 
      array (
		'text' => '열람 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Read'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Read',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
	  9 => 
      array (
		'text' => '1:1 비밀 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=secret&bo_skin=BS4-MBS-Secret'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-secret-BS4-MBS-Secret',
		'bo_table' => 'secret',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      10 => 
      array (
		'text' => '피드 수집 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Feed'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Feed',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
	  11 => 
      array (
		'text' => '태그 분류 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Tags'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Tags',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      12 => 
      array (
		'text' => '댓글 별점 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Star'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Star',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
      13 => 
      array (
		'text' => '유튜브 검색 보드',
		'href' => short_url_clean(G5_BBS_URL.'/board.php?bo_table=board&bo_skin=BS4-MBS-Youtube'),
		'icon' => 'empty',
		'target' => '_self',
		'line' => '',
		'sp' => '',
		'limit' => '',
		'grade' => 0,
		'id' => G5_BBS_DIR.'-board-board-BS4-MBS-Youtube',
		'bo_table' => 'board',
		'wr_id' => NULL,
		'sca' => NULL,
      ),
	),
  ),
  4 => 
  array (
    'text' => '페이지',
	'href' => short_url_clean(G5_BBS_URL.'/group.php?gr_id=demo'),
	'icon' => 'empty',
	'target' => '_self',
	'line' => '',
	'sp' => '',
	'limit' => '',
	'grade' => 0,
	'id' => G5_BBS_DIR.'-group-demo',
	'gr_id' => 'demo',
	's' => 
    array (
      0 => 
      array (
        'text' => '그룹메인',
        'href' => short_url_clean(G5_BBS_URL.'/group.php?gr_id=demo'),
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-group-demo',
        'gr_id' => 'demo',
      ),
	  1 => 
      array (
        'text' => '새글모음',
        'href' => G5_BBS_URL.'/new.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-new',
      ),
	  2 => 
      array (
        'text' => '태그모음',
        'href' => G5_BBS_URL.'/tag.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-tag',
      ),
	  3 => 
      array (
        'text' => '전체검색',
        'href' => G5_BBS_URL.'/search.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-search',
      ),
	  4 => 
      array (
        'text' => 'FAQ',
        'href' => G5_BBS_URL.'/faq.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-faq',
      ),
      5 => 
      array (
        'text' => '접속자',
        'href' => G5_BBS_URL.'/current_connect.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-current_connect',
      ),
      6 => 
      array (
        'text' => '알림모음',
        'href' => G5_BBS_URL.'/noti.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '회원전용',
        'sp' => '1',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-noti',
      ),
	  7 => 
      array (
        'text' => '신고모음',
        'href' => G5_BBS_URL.'/shingo.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-page-shingo',
      ),
      8 => 
      array (
        'text' => '1:1문의',
        'href' => G5_BBS_URL.'/qalist.php',
        'icon' => 'empty',
        'target' => '_self',
        'line' => '',
        'sp' => '',
        'limit' => '',
        'grade' => 0,
        'id' => G5_BBS_DIR.'-qa',
      ),
    ),
  ),
  5 => 
  array (
    'text' => '나리야빌더',
    'href' => 'https://amina.co.kr/nariya',
    'icon' => 'empty',
    'target' => '_blank',
    'line' => '',
    'sp' => '',
    'limit' => '',
    'grade' => 0,
    'id' => 'link',
  ),
);