<?php
if (!defined('_GNUBOARD_')) exit;
$data=array (
  'seo' => '1',
  'seo_desc' => '',
  'seo_keys' => '',
  'seo_img' => '',
  'logo_img' => '../img/logo.png',
  'logo_text' => '',
  'stats' => '10',
  'noti' => '30',
  'font' => 'NEXON-Gothic-14px',
  'font_mo' => 'Default-15px',
  'no_res' => '0',
  'layout' => 'w',
  'size' => '1100',
  'bg_img' => '',
  'bg_pos' => 'center',
  'wing' => '0',
  'color' => 'Blue',
  'style' => '0',
  'line' => '0',
  'menu' => '1',
  'menu_w' => '4',
  'sub_w' => '150',
  'sub_pc' => '0',
  'sticky' => '0',
  'index' => 'index-basic',
  'pwide' => '0',
  'pmax' => '1980',
  'ptitle' => '0',
  'scol' => '3',
  'sfile' => 'side-basic',
  'sloc' => 'right',
  'ftstyle' => 'box',
);